name: test_sync_warehouse

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次，可以根据需要调整
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write  # 允许写入内容,使用 GitHub Actions 提供的默认 `GITHUB_TOKEN`

jobs:
  pull_mblog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12.3'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install Pip Package
        run: pip install jupyter nbconvert pandas pelican
      
      - name: Show Pip List Package
        run: pip list

      - name: Clone Current Repository
        uses: actions/checkout@main
        with:
          repository: YZSH-HSZY/yzsh-hszy.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          path: yzsh-repo

      - name: Clone Github Repository Mblog
        run: |
          git clone https://github.com/YZSH-HSZY/mblog.git mblog-repo
      
      - name: Convert Ipynb To Markdown
        run: cd mblog-repo && find ./ -iname "*.ipynb" | xargs jupyter nbconvert --to markdown

      - name: Copy MD Files To Current Repository
        run: |
          echo $(pwd) && ls -R
          cp -r mblog-repo/* yzsh-repo/content/ 
          cd yzsh-repo/content 
          find ./ -type f | grep -E -v "*\.md$" | xargs rm -rf
          echo "the yzsh-repo content"
          ls -R ./
      
      - name: Convert MD Files To Static Html Files
        run: |
          cd yzsh-repo
          pelican content -D -s ./_scripts/publishconf.py -o .

      - name: Commit and Push Content Changes
        run: |
          cd yzsh-repo
          git config user.name "YZSH-HSZY"
          git config user.email "yzsh_hszy@outlook.com"
          git add content
          git commit -m "Sync from other warehouse and auto deploy" || echo "No content changes to commit"
          git push origin main  # 根据你的主分支名称调整
# on:
#   # push: # push 时触发, 主要是为了测试配置有没有问题
#   schedule:
#     - cron: '* */3 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: TG908/fork-sync@v1.6.3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           owner: ZhaoUncle # fork 的上游仓库 user
#           head: main # fork 的上游仓库 branch
#           base: main # 本地仓库 branch